driver:
  name: dokken
  privileged: true # because Docker and SystemD/Upstart
  chef_version: <%= ENV['CHEF_VERSION'] || 'current' %>

transport:
  name: dokken

provisioner:
  name: dokken
  chef_options: '-z --chef-zero-port 9010'

verifier:
  name: inspec

platforms:
- name: amazonlinux
  driver:
    image: dokken/amazonlinux
    pid_one_command: /sbin/init
    intermediate_instructions:
      - RUN yum install -y crontabs

- name: debian-7
  driver:
    image: dokken/debian-7
    pid_one_command: /sbin/init
    intermediate_instructions:
      - RUN /usr/bin/apt-get update

- name: debian-8
  driver:
    image: dokken/debian-8
    pid_one_command: /bin/systemd
    intermediate_instructions:
      - RUN /usr/bin/apt-get update

- name: debian-9
  driver:
    image: dokken/debian-9
    pid_one_command: /bin/systemd
    intermediate_instructions:
      - RUN /usr/bin/apt-get update

- name: centos-6
  driver:
    image: dokken/centos-6
    pid_one_command: /sbin/init
    intermediate_instructions:
      - RUN yum install -y crontabs

- name: centos-7
  driver:
    image: dokken/centos-7
    pid_one_command: /usr/lib/systemd/systemd
    intermediate_instructions:
      - RUN yum install -y crontabs

- name: ubuntu-14.04
  driver:
    image: dokken/ubuntu-14.04
    pid_one_command: /sbin/init
    intermediate_instructions:
      - RUN /usr/bin/apt-get update

- name: ubuntu-16.04
  driver:
    image: dokken/ubuntu-16.04
    pid_one_command: /bin/systemd
    intermediate_instructions:
      - RUN /usr/bin/apt-get update
      - RUN /usr/bin/apt-get install -y tzdata cron

suites:
- name: default
  run_list:
  - recipe[test::default]
- name: no-fqdn
  run_list:
  - recipe[test::no-fqdn]
  driver:
    network:
      - ['private_network', {ip: '192.168.243.2'}]
- name: add-ons-no-fqdn
  run_list:
  - recipe[test::add-ons-no-fqdn]
  driver:
    network:
      - ['private_network', {ip: '192.168.243.3'}]
